"""
Project scaffold templates for SkyGround Agent.

These templates let the agent create new projects from zero without relying on UI actions.
They are intentionally small, understandable, and easy for the agent/user to modify later.
"""

from __future__ import annotations

import dataclasses
import re
from typing import Dict, List


@dataclasses.dataclass(frozen=True)
class ScaffoldResult:
    template: str
    project_name: str
    description: str
    files: Dict[str, str]
    run_commands: List[str]
    next_steps: List[str]


SAFE_PROJECT_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def safe_project_name(name: str) -> str:
    name = (name or "").strip().replace(" ", "_")
    if not name:
        raise ValueError("project_name is required")
    if name in {".", ".."} or "/" in name or "\\" in name:
        raise ValueError("project_name must be a simple folder name, not a path")
    if not SAFE_PROJECT_RE.match(name):
        raise ValueError("project_name may only contain letters, numbers, underscore, dash, and dot")
    return name


def _title(name: str) -> str:
    return name.replace("_", " ").replace("-", " ").title()


def list_templates() -> List[Dict[str, str]]:
    return [
        {"id": "python_flask_site", "label": "Python Flask Website", "description": "Small Flask website with templates/static files."},
        {"id": "python_fastapi_api", "label": "Python FastAPI API", "description": "Small FastAPI backend with health and items endpoints."},
        {"id": "static_html_site", "label": "Static HTML Site", "description": "Simple HTML/CSS/JS site with no backend."},
        {"id": "python_cli_tool", "label": "Python CLI Tool", "description": "Small argparse-based command line tool."},
    ]


def create_scaffold(template: str, project_name: str, description: str = "") -> ScaffoldResult:
    project_name = safe_project_name(project_name)
    template = (template or "").strip()
    description = (description or "").strip() or f"A new {template} project generated by SkyGround."
    if template == "python_flask_site":
        return python_flask_site(project_name, description)
    if template == "python_fastapi_api":
        return python_fastapi_api(project_name, description)
    if template == "static_html_site":
        return static_html_site(project_name, description)
    if template == "python_cli_tool":
        return python_cli_tool(project_name, description)
    raise ValueError(f"Unknown scaffold template: {template}")


def python_flask_site(project_name: str, description: str) -> ScaffoldResult:
    title = _title(project_name)
    files = {
        "README.md": f"""# {title}\n\n{description}\n\n## Setup\n\n```powershell\npython -m venv .venv\n.\\.venv\\Scripts\\python -m pip install -r requirements.txt\n.\\.venv\\Scripts\\python app.py\n```\n\nOpen:\n\n```text\nhttp://127.0.0.1:5000\n```\n\n## Structure\n\n```text\napp.py\ntemplates/index.html\nstatic/style.css\n```\n""",
        "requirements.txt": "Flask>=3.0,<4\n",
        "app.py": """from flask import Flask, render_template\n\napp = Flask(__name__)\n\n\n@app.route(\"/\")\ndef index():\n    return render_template(\"index.html\")\n\n\n@app.route(\"/health\")\ndef health():\n    return {\"status\": \"ok\"}\n\n\nif __name__ == \"__main__\":\n    app.run(host=\"127.0.0.1\", port=5000, debug=True)\n""",
        "templates/index.html": f"""<!doctype html>\n<html lang=\"fa\" dir=\"rtl\">\n<head>\n  <meta charset=\"utf-8\" />\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n  <title>{title}</title>\n  <link rel=\"stylesheet\" href=\"{{{{ url_for('static', filename='style.css') }}}}\" />\n</head>\n<body>\n  <main class=\"hero\">\n    <section class=\"card\">\n      <p class=\"eyebrow\">ساخته شده با Flask</p>\n      <h1>{title}</h1>\n      <p>{description}</p>\n      <a class=\"button\" href=\"/health\">بررسی سلامت API</a>\n    </section>\n  </main>\n</body>\n</html>\n""",
        "static/style.css": """:root {\n  color-scheme: dark;\n  font-family: Tahoma, system-ui, -apple-system, Segoe UI, sans-serif;\n  background: #0f172a;\n  color: #e5eefb;\n}\n\nbody {\n  margin: 0;\n  min-height: 100vh;\n  background: radial-gradient(circle at top, #1e3a8a 0, #0f172a 42%, #020617 100%);\n}\n\n.hero {\n  min-height: 100vh;\n  display: grid;\n  place-items: center;\n  padding: 32px;\n}\n\n.card {\n  width: min(760px, 92vw);\n  padding: 42px;\n  border: 1px solid rgba(148, 163, 184, 0.28);\n  border-radius: 28px;\n  background: rgba(15, 23, 42, 0.78);\n  box-shadow: 0 24px 80px rgba(0, 0, 0, 0.42);\n}\n\n.eyebrow {\n  color: #67e8f9;\n  font-weight: 700;\n}\n\nh1 {\n  font-size: clamp(34px, 7vw, 72px);\n  margin: 0 0 18px;\n}\n\np {\n  line-height: 1.9;\n  color: #cbd5e1;\n}\n\n.button {\n  display: inline-block;\n  margin-top: 18px;\n  padding: 12px 18px;\n  border-radius: 14px;\n  color: #082f49;\n  background: #67e8f9;\n  text-decoration: none;\n  font-weight: 800;\n}\n""",
        ".gitignore": ".venv/\n__pycache__/\n*.pyc\n.env\n.sg_agent/\n",
    }
    return ScaffoldResult(
        template="python_flask_site",
        project_name=project_name,
        description=description,
        files=files,
        run_commands=[
            "python -m venv .venv",
            ".\\.venv\\Scripts\\python -m pip install -r requirements.txt",
            ".\\.venv\\Scripts\\python app.py",
        ],
        next_steps=["Open http://127.0.0.1:5000", "Edit templates/index.html and static/style.css"],
    )


def python_fastapi_api(project_name: str, description: str) -> ScaffoldResult:
    title = _title(project_name)
    files = {
        "README.md": f"""# {title}\n\n{description}\n\n## Setup\n\n```powershell\npython -m venv .venv\n.\\.venv\\Scripts\\python -m pip install -r requirements.txt\n.\\.venv\\Scripts\\python -m uvicorn main:app --reload\n```\n\nDocs:\n\n```text\nhttp://127.0.0.1:8000/docs\n```\n""",
        "requirements.txt": "fastapi>=0.110,<1\nuvicorn[standard]>=0.27,<1\n",
        "main.py": f"""from fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI(title=\"{title}\")\n\n\nclass Item(BaseModel):\n    name: str\n    description: str | None = None\n\n\n@app.get(\"/\")\ndef root():\n    return {{\"message\": \"Welcome to {title}\"}}\n\n\n@app.get(\"/health\")\ndef health():\n    return {{\"status\": \"ok\"}}\n\n\n@app.post(\"/items\")\ndef create_item(item: Item):\n    return {{\"ok\": True, \"item\": item}}\n""",
        ".gitignore": ".venv/\n__pycache__/\n*.pyc\n.env\n.sg_agent/\n",
    }
    return ScaffoldResult("python_fastapi_api", project_name, description, files, ["python -m venv .venv", ".\\.venv\\Scripts\\python -m pip install -r requirements.txt", ".\\.venv\\Scripts\\python -m uvicorn main:app --reload"], ["Open http://127.0.0.1:8000/docs"])


def static_html_site(project_name: str, description: str) -> ScaffoldResult:
    title = _title(project_name)
    files = {
        "README.md": f"# {title}\n\n{description}\n\nOpen `index.html` in your browser.\n",
        "index.html": f"""<!doctype html>\n<html lang=\"fa\" dir=\"rtl\">\n<head>\n  <meta charset=\"utf-8\" />\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n  <title>{title}</title>\n  <link rel=\"stylesheet\" href=\"static/style.css\" />\n</head>\n<body>\n  <main class=\"container\">\n    <h1>{title}</h1>\n    <p>{description}</p>\n    <button id=\"hello\">کلیک کن</button>\n  </main>\n  <script src=\"static/app.js\"></script>\n</body>\n</html>\n""",
        "static/style.css": """body {\n  margin: 0;\n  min-height: 100vh;\n  display: grid;\n  place-items: center;\n  font-family: Tahoma, sans-serif;\n  background: linear-gradient(135deg, #0f172a, #1e3a8a);\n  color: white;\n}\n.container {\n  width: min(720px, 92vw);\n  padding: 36px;\n  border-radius: 24px;\n  background: rgba(255,255,255,0.08);\n}\nbutton {\n  padding: 12px 18px;\n  border: 0;\n  border-radius: 12px;\n  cursor: pointer;\n}\n""",
        "static/app.js": """document.getElementById('hello')?.addEventListener('click', () => {\n  alert('سلام از سایت ساخته‌شده با SkyGround!');\n});\n""",
        ".gitignore": ".sg_agent/\n",
    }
    return ScaffoldResult("static_html_site", project_name, description, files, ["start index.html"], ["Open index.html in a browser"])


def python_cli_tool(project_name: str, description: str) -> ScaffoldResult:
    title = _title(project_name)
    module_name = re.sub(r"[^A-Za-z0-9_]", "_", project_name).lower()
    files = {
        "README.md": f"""# {title}\n\n{description}\n\n## Run\n\n```powershell\npython main.py --name Ali\n```\n""",
        "main.py": f"""import argparse\n\n\ndef main() -> int:\n    parser = argparse.ArgumentParser(description={description!r})\n    parser.add_argument(\"--name\", default=\"World\", help=\"Name to greet\")\n    args = parser.parse_args()\n    print(f\"Hello, {{args.name}}! This is {title}.\")\n    return 0\n\n\nif __name__ == \"__main__\":\n    raise SystemExit(main())\n""",
        "tests/test_basic.py": f"""import subprocess\nimport sys\n\n\ndef test_cli_runs():\n    result = subprocess.run([sys.executable, \"main.py\", \"--name\", \"Test\"], capture_output=True, text=True)\n    assert result.returncode == 0\n    assert \"Test\" in result.stdout\n""",
        ".gitignore": "__pycache__/\n*.pyc\n.pytest_cache/\n.sg_agent/\n",
    }
    return ScaffoldResult("python_cli_tool", project_name, description, files, ["python main.py --name Ali", "python -m pytest"], ["Add your CLI logic in main.py"])